apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# CI/CD Umgebung
resources:
  - ../../base

patches:
  # Docker Image von GitHub Container Registry verwenden
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/jonessy05/gitpython/reservations-api:latest
    target:
      group: apps
      version: v1
      kind: Deployment
      name: reservations
  
  # ImagePullPolicy auf "IfNotPresent" (Pull von Registry wenn nicht lokal)
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      group: apps
      version: v1
      kind: Deployment
      name: reservations
